"""Corner rounding as a GEOMETRY TYPE: a sharp backbone plus a per-corner radius ``rho``.

This revives Phase 2's ``roundify`` (``scrap/geometry.py``, ``notes/roundedDefinitions.tex``) with the
notation of those notes unchanged, and adds the one thing they lacked -- derivatives with respect to
``rho`` itself, so the radii can be degrees of freedom rather than inputs.

    t_i   = rho_i / tan(theta_i / 2)                 kiss offset along each incident edge
    a^-_i = v_i - t_i eInHat_i,  a^+_i = v_i + t_i eOutHat_i      kiss points
    z_i   = v_i + (rho_i / sin(theta_i / 2)) bHat_i               circle center
    psi_i = pi - theta_i                                          arc sweep

THE BACKBONE IS THE STATE, THE ROUNDED LOOP IS DERIVED. The polygon that is constrained, sprung and
reported is the sharp backbone; the rounded loop is what the contact tier actually sees. So area and
edge constraints keep meaning exactly what they meant, and ``rho`` only ever REMOVES material:

    A_rounded = A_backbone - sum_i (rho_i t_i - rho_i^2 psi_i / 2)

At a right angle ``t_i = rho_i`` and ``psi_i = pi/2``, so each corner costs ``rho^2 (4 - pi) / 4`` and a
square of side L with four equal radii loses ``(4 - pi) rho^2`` -- the familiar rounded-square area.

FEASIBILITY IS A PER-EDGE CONDITION, NOT A PER-CORNER ONE. Each edge must fit the two kiss offsets it
carries, ``t_k + t_next <= |e_k|``. For a square with equal radii that is ``2 rho <= L``, i.e.
``rho <= L/2``, where the four arcs meet and the shape is a disk. Equivalently the center sits at
``rho sqrt(2)`` along the diagonal and may not pass the square's own center at ``(L/2) sqrt(2)`` -- the
same bound read along the diagonal.

THE ARCS ARE CHORDED. Exact rounded contact under the depth law needs ``(d + r)^3`` integrated along a
circular arc against polygon features, whose arc-versus-vertex case is an ELLIPTIC integral. Chording
each corner into ``segments`` pieces keeps every existing tier -- the area law, the depth law, their
CUDA kernels, the wall by winding -- working unchanged on an ordinary polygon. At ``rho = 0`` the arc
collapses to the corner and the shape is EXACTLY the sharp backbone, so the approximation lives
entirely on the path and never in the endpoint.

THE JACOBIAN IS TAKEN BY COMPLEX STEP, and that is a correctness decision rather than a shortcut.
``d(rounded vertex)/d(backbone vertex, rho)`` is differentiated from the SAME function that builds the
loop, so the two can never drift apart, and the complex step has no subtractive cancellation -- it is
exact to machine precision rather than to a step size. Each arc point depends on only four inputs
(``v_prev``, ``v_self``, ``v_next``, ``rho``), so the whole sparse Jacobian costs seven vectorized
evaluations regardless of the polygon count.

VERTEX COUNTS ARE NEVER ASSUMED UNIFORM. Everything is driven off CSR ``startIndices`` with ``prev`` /
``next`` indices, so ragged polygons and the container ride the same path.
"""

# UNVERIFIED(Cam)

import numpy as np

# The complex step. Any value far below sqrt(machine epsilon) works -- there is no cancellation to
# trade against, which is the whole reason for using it instead of a finite difference.
_STEP = 1e-30


# UNVERIFIED(Cam)
def cornerFrame(previous, current, following, rho):
    """``(t, z, aMinus, aPlus, psi, theta)`` for corners given their three vertices and radius.

    Takes the three vertices as SEPARATE arrays rather than indexing one array, which is what lets the
    complex step perturb a single role at a time. Every operation is analytic in its inputs -- lengths
    are ``sqrt(x^2 + y^2)`` rather than ``abs``, and nothing is clipped -- so the same code runs on
    complex input and returns a derivative in its imaginary part.

    ``theta`` is the interior wedge angle ``arccos(-eInHat . eOutHat)``; it is left unclipped on
    purpose, because clipping is not analytic and a corner that needs it is degenerate anyway."""
    incoming = current - previous
    outgoing = following - current
    inHat = incoming / np.sqrt(incoming[:, 0] ** 2 + incoming[:, 1] ** 2)[:, None]
    outHat = outgoing / np.sqrt(outgoing[:, 0] ** 2 + outgoing[:, 1] ** 2)[:, None]

    theta = np.arccos(-(inHat[:, 0] * outHat[:, 0] + inHat[:, 1] * outHat[:, 1]))
    half = 0.5 * theta
    t = rho / np.tan(half)

    aMinus = current - t[:, None] * inHat
    aPlus = current + t[:, None] * outHat

    bisector = outHat - inHat
    bHat = bisector / np.sqrt(bisector[:, 0] ** 2 + bisector[:, 1] ** 2)[:, None]
    z = current + (rho / np.sin(half))[:, None] * bHat
    return t, z, aMinus, aPlus, np.pi - theta, theta


# UNVERIFIED(Cam)
def arcPoints(previous, current, following, rho, sweepSign, segments):
    """``(M, segments + 1, 2)`` points along each corner's arc, from ``a^-`` to ``a^+``.

    The arc is generated by ROTATING ``a^- - z`` rather than by building an absolute angle, so no
    ``arctan2`` appears and the map stays analytic for the complex step. ``sweepSign`` is +1 at a
    convex corner and -1 at a reflex one; it is computed once from the real geometry and passed in as a
    constant, because a sign is a comparison and comparisons do not differentiate.

    At ``rho = 0`` every point of the arc collapses onto the vertex. The caller is responsible for
    dropping the duplicates -- a zero-length edge has no tangent, and the contact law divides by
    exactly that."""
    _, z, aMinus, _, psi, _ = cornerFrame(previous, current, following, rho)
    radius = aMinus - z
    fractions = np.linspace(0.0, 1.0, int(segments) + 1)
    angles = (sweepSign * psi)[:, None] * fractions[None, :]
    cosine, sine = np.cos(angles), np.sin(angles)
    x = z[:, 0][:, None] + cosine * radius[:, 0][:, None] - sine * radius[:, 1][:, None]
    y = z[:, 1][:, None] + sine * radius[:, 0][:, None] + cosine * radius[:, 1][:, None]
    return np.stack([x, y], axis = -1)


# UNVERIFIED(Cam)
def convexSign(positions, previousIndex, nextIndex):
    """+1 at convex (left-turning) corners of a counter-clockwise loop, -1 at reflex ones."""
    r = np.asarray(positions, dtype = float).reshape(-1, 2)
    incoming = r - r[previousIndex]
    outgoing = r[nextIndex] - r
    cross = incoming[:, 0] * outgoing[:, 1] - incoming[:, 1] * outgoing[:, 0]
    return np.where(cross >= 0.0, 1.0, -1.0)


# UNVERIFIED(Cam)
def roundedStartIndices(startIndices, segments):
    """CSR offsets of the rounded packing: each backbone vertex becomes ``segments + 1`` of them."""
    counts = np.diff(np.asarray(startIndices, dtype = int)) * (int(segments) + 1)
    return np.concatenate([[0], np.cumsum(counts)]).astype(int)


# UNVERIFIED(Cam)
def roundedPositions(positions, previousIndex, nextIndex, rho, sweepSign, segments):
    """Flat ``(2 * M * (segments + 1),)`` rounded coordinates, in backbone vertex order.

    Corner ``k`` contributes its whole arc before corner ``k + 1`` begins, so the straight runs between
    kiss points appear implicitly as the chords from ``a^+_k`` to ``a^-_{k+1}`` and the loop comes out
    correctly wound with no separate bookkeeping."""
    r = np.asarray(positions).reshape(-1, 2)
    points = arcPoints(r[previousIndex], r, r[nextIndex], rho, sweepSign, segments)
    return points.reshape(-1)


# UNVERIFIED(Cam)
def roundedJacobianApply(positions, previousIndex, nextIndex, rho, sweepSign, segments, gradient):
    """Pull a gradient back from the rounded loop to ``(backbone vertices, rho)``.

    Returns ``(backboneGradient, rhoGradient)`` with shapes ``(M, 2)`` and ``(M,)``. This is
    ``J^T g``, taken by complex-stepping the four inputs each arc point actually depends on -- seven
    passes total (two components each for the previous, own and next vertex, plus ``rho``), whatever
    the polygon count or its raggedness.

    The three vertex roles are accumulated with ``np.add.at`` rather than by assignment, because a
    vertex is the previous, own and next of three different corners and all three contributions are
    real."""
    r = np.asarray(positions, dtype = float).reshape(-1, 2)
    rho = np.asarray(rho, dtype = float)
    g = np.asarray(gradient, dtype = float).reshape(-1, int(segments) + 1, 2)

    previous, current, following = r[previousIndex], r, r[nextIndex]
    backbone = np.zeros_like(r)
    rhoGradient = np.zeros_like(rho)

    def sensitivity(shifted):
        """d(arc points)/d(that input), from the imaginary part of one complex evaluation."""
        points = arcPoints(*shifted, sweepSign, segments)
        return points.imag / _STEP

    for component in (0, 1):
        bump = np.zeros((len(r), 2), dtype = complex)
        bump[:, component] = 1j * _STEP

        derivative = sensitivity((previous + bump, current.astype(complex),
                                  following.astype(complex), rho.astype(complex)))
        np.add.at(backbone, previousIndex, np.sum(derivative * g, axis = (1, 2))[:, None]
                  * np.eye(2)[component])

        derivative = sensitivity((previous.astype(complex), current + bump,
                                  following.astype(complex), rho.astype(complex)))
        backbone[:, component] += np.sum(derivative * g, axis = (1, 2))

        derivative = sensitivity((previous.astype(complex), current.astype(complex),
                                  following + bump, rho.astype(complex)))
        np.add.at(backbone, nextIndex, np.sum(derivative * g, axis = (1, 2))[:, None]
                  * np.eye(2)[component])

    derivative = sensitivity((previous.astype(complex), current.astype(complex),
                              following.astype(complex), rho + 1j * _STEP))
    rhoGradient += np.sum(derivative * g, axis = (1, 2))
    return backbone, rhoGradient


# UNVERIFIED(Cam)
def cornerAreaLoss(positions, previousIndex, nextIndex, rho):
    """Per-corner area removed by the rounding, ``rho t - rho^2 psi / 2`` (notes eq for the kite minus
    the wedge). Sums to ``A_backbone - A_rounded``."""
    r = np.asarray(positions, dtype = float).reshape(-1, 2)
    t, _, _, _, psi, _ = cornerFrame(r[previousIndex], r, r[nextIndex],
                                     np.asarray(rho, dtype = float))
    return rho * t - 0.5 * rho ** 2 * psi


# UNVERIFIED(Cam)
def edgeSlack(positions, previousIndex, nextIndex, rho):
    """``|e_k| - t_k - t_next`` on every edge: the feasibility margin, negative where rounding fails.

    THIS IS THE CONSTRAINT THAT BITES, not a per-corner cap. Two corners share an edge and each eats
    ``t`` of it, so a radius that is fine on its own can be infeasible next to a large neighbor."""
    r = np.asarray(positions, dtype = float).reshape(-1, 2)
    t, _, _, _, _, _ = cornerFrame(r[previousIndex], r, r[nextIndex], np.asarray(rho, dtype = float))
    outgoing = r[nextIndex] - r
    return np.hypot(outgoing[:, 0], outgoing[:, 1]) - t - t[nextIndex]


# UNVERIFIED(Cam)
def maxRho(positions, previousIndex, nextIndex, safety = 1.0):
    """Largest EQUAL radius every corner could take, per vertex: ``|e| / (cot(a/2) + cot(b/2))``.

    At a square this is half the edge length, where the four arcs meet and the shape becomes a disk.
    Multiply by ``safety`` below 1 to keep a margin off the degenerate limit."""
    r = np.asarray(positions, dtype = float).reshape(-1, 2)
    unit = np.ones(len(r))
    t, _, _, _, _, _ = cornerFrame(r[previousIndex], r, r[nextIndex], unit)
    outgoing = r[nextIndex] - r
    length = np.hypot(outgoing[:, 0], outgoing[:, 1])
    perEdge = length / (t + t[nextIndex])
    return float(safety) * np.minimum(perEdge, perEdge[previousIndex])


# UNVERIFIED(Cam)
def dropDuplicates(positions, startIndices, tolerance = 1e-9):
    """Drop coincident consecutive vertices, returning ``(positions, startIndices, keep)``.

    Needed at both ends of the path: at ``rho = 0`` a corner's whole arc collapses onto the vertex, and
    at the feasible limit the straight runs vanish so neighboring arcs share an endpoint. A zero-length
    edge has no tangent and the contact law divides by exactly that."""
    r = np.asarray(positions, dtype = float).reshape(-1, 2)
    starts = np.asarray(startIndices, dtype = int)
    keep = np.ones(len(r), dtype = bool)
    for polygon in range(len(starts) - 1):
        block = slice(starts[polygon], starts[polygon + 1])
        loop = r[block]
        step = loop - np.roll(loop, 1, axis = 0)
        keep[block] = np.hypot(step[:, 0], step[:, 1]) > tolerance
    counts = np.array([int(keep[starts[p]:starts[p + 1]].sum()) for p in range(len(starts) - 1)])
    return r[keep], np.concatenate([[0], np.cumsum(counts)]).astype(int), keep
