"""Measure how the energy scales with distance above the jamming density, and use it to locate phi_J.

WHAT IS BEING MEASURED. Above jamming a packing cannot avoid overlapping, and the cost grows as a
power law in the distance from the transition,

    E ~ (phi - phi_J)^alpha,        P = phi dE/dphi ~ (phi - phi_J)^(alpha - 1).

The exponent is set by the CONTACT LAW. Our overlap energy is U = 2 sum (a / norm)^2 with ``a`` the
overlap AREA, and a flat face contact of width w and depth d has a ~ w d, so U ~ d^2 -- harmonic.
That predicts alpha = 2, the O'Hern/Silbert/Liu/Nagel soft-sphere result. The sweep is written to
FALSIFY that, not to assume it: alpha is fitted freely and the harmonic prediction is reported as a
comparison.

WHY IT IS WORTH HAVING. Bisecting on "is the energy below a threshold" needs a threshold, and near
jamming the answer is dominated by whatever floor the mollification imposes. A power law gives a
better instrument: E^(1/alpha) is LINEAR in phi, so a few points comfortably ABOVE the transition
extrapolate to phi_J without ever simulating at phi_J, where relaxation is critically slow.

PROTOCOL. One branch, compressed. A configuration is relaxed at a low phi and then squeezed upward in
small steps, re-relaxing at each -- ``setPackingFraction`` scales polygons and their targets together,
so hard area constraints stay satisfied and no shape can shrink to relieve the stress. Rebuilding a
fresh random packing at every phi instead would sample a different basin each time and turn the
scaling curve into noise.

TWO THINGS THAT WILL BITE.
  * MOLLIFICATION FLOOR. sigma smooths the contact, so below overlap ~ sigma the energy is not the
    sharp power law at all. The sweep is run at several sigma and the fit restricted to the region
    where the answer stops depending on it.
  * phi_J IS NOT THE OPTIMAL PACKING DENSITY. Compressing a random branch jams wherever that branch
    jams, generally BELOW the densest packing (0.6823 for 5 squares). alpha is the universal quantity;
    phi_J is protocol- and seed-dependent, so it is reported per seed with its spread.

Run: python tests/energySweep.py [--squares 5] [--seeds 3]
"""

import argparse
import math
import os
import sys
import warnings

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from model import Model

WALL = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 1.0], [1.0, 0.0]])


def tiles(numSquares):
    """Whether N congruent squares TILE the unit torus, i.e. whether N is a sum of two squares.

    Cam's criterion, verified constructively. A tiling by squares of side 1/sqrt(N) is invariant under
    a SQUARE lattice of covolume 1/N, and for it to descend to the unit torus that lattice must contain
    Z^2 with index N. The square sublattices of Z^2 are exactly those generated by (a, b) and (-b, a) --
    the Gaussian integers -- of index a^2 + b^2. The squares are then rotated by atan2(b, a), which is
    why N = 8 = 2^2 + 2^2 tiles at 45 degrees.

    This matters for a jamming study: if N tiles, rigid squares reach phi = 1 with ZERO overlap and
    there is no transition to measure anywhere below it. 4, 5, 8, 9, 10 all tile -- so N must be drawn
    from 3, 6, 7, 11, 12, 14, 15, ... instead."""
    for a in range(math.isqrt(numSquares) + 1):
        remainder = numSquares - a * a
        root = math.isqrt(remainder)
        if root * root == remainder:
            return True
    return False


def buildPacking(numSquares, seed, phi, softening, rigid = True, boundary = "periodic", sides = 4):
    """A relaxed rigid packing ready to be compressed.

    ``boundary`` selects a PERIODIC cell (which the sharp tier supports, and which has no wall to
    contaminate a finite-size measurement) or a fixed unit container (which the sharp tier does not
    yet support -- ``energies.containerEnergyForce`` is mollified-only)."""
    model = Model(N = numSquares, n = sides, seed = seed)
    kappa = float(np.sqrt(4.0 * sides * np.tan(np.pi / sides)))
    model.generateEquilateralPolygons(phi = phi, kappa = kappa)
    model.setMonoPerimeter()
    if boundary == "fixed":
        model.addShape(WALL)
        model.pinVertices(np.arange(model.getNumVertices())[-4:])
        model.setBoundaryConditions("fixed")
    else:
        model.setBoundaryConditions("periodic")
    model.setModelType("mollified")
    model.setSofteningFraction(softening)
    # RIGID is not optional for this measurement. With springs the squares relieve stress by
    # shrinking -- measured A/A_target = 0.985 at phi = 0.80 -- which lowers the true packing fraction
    # while the nominal one keeps rising, and the exponent measured against a phi that is not the real
    # phi is meaningless.
    if rigid:
        model.setConstraints(area = True, edge = True)
    else:
        model.setSpringConstants()
    return model


def relax(model, tolerance, maxSteps):
    """FIRE then a CG polish; returns the residual actually reached.

    The polish matters here: the fit is over several decades of energy, and a residual left at FIRE's
    linear-convergence rate biases the low-energy end -- exactly the end that sets phi_J."""
    model.minimizeFIRE(maxUnbalancedForce = tolerance, maxSteps = maxSteps)
    model.minimizeCG(maxUnbalancedForce = tolerance, maxSteps = 400)
    return model.getMaxUnbalancedForce()


def sharpEnergy(model):
    """The EXACT (unmollified) overlap energy of the current configuration.

    The honest indicator, and the reason it is worth the model switch: the mollified energy does not
    vanish on a valid packing -- measured 8.2e-04 for 8 squares at phi = 0.99 whose true overlap is
    exactly ZERO -- because its kernel has a tail between merely-touching faces. It reports proximity,
    not overlap, and it RISES as a perfectly valid packing is compressed. Thresholding it is what made
    the earlier packs-versus-jams verdicts need a hand-tuned, sigma-dependent cutoff.

    The sharp area is identically zero below jamming and positive above, verified against independent
    Sutherland-Hodgman clipping and Monte Carlo coverage on six configurations. So it turns "has this
    jammed?" from a threshold judgement into a sign change. Relax with the mollified energy, which is
    smooth and converges; MEASURE with this one."""
    model.setModelType("sharp")
    model.calcForceEnergy()
    value = model.getEnergy()
    model.setModelType("mollified")
    model.calcForceEnergy()
    return value


def jammingDensity(numSquares, seed, softening, phiLow = 0.55, phiHigh = 0.99, rounds = 14,
                   tolerance = 1e-9, maxSteps = 6000, sides = 4):
    """Bisect the packing fraction at which the SHARP overlap first becomes nonzero.

    One branch throughout: the configuration is carried from one phi to the next by
    ``setPackingFraction`` rather than rebuilt, so this follows a single state up in density.

    Read this as protocol-dependent, and as an UPPER bound on what is geometrically possible. A
    nonzero sharp energy proves the relaxation did not FIND a valid packing, not that none exists --
    measured directly: 9 squares tile the torus exactly, yet compression from a random start left
    2.7e-04 of overlap at phi = 0.99. Different seeds therefore give genuinely different answers, and
    the spread is the honest error bar."""
    model = buildPacking(numSquares, seed, phiLow, softening, sides = sides)
    relax(model, tolerance, maxSteps)
    if sharpEnergy(model) > 0.0:
        return np.nan, model
    low, high = phiLow, phiHigh
    for _ in range(rounds):
        middle = 0.5 * (low + high)
        model.setPackingFraction(middle)
        relax(model, tolerance, maxSteps)
        if sharpEnergy(model) > 0.0:
            high = middle
        else:
            low = middle
    return high, model


def sweep(numSquares, seed, softening, phiLow, phiHigh, points, tolerance = 1e-9,
          maxSteps = 4000, rigid = True):
    """Compress one branch from ``phiLow`` to ``phiHigh``, relaxing at each step.

    Returns a structured array with phi, energy, residual, the area-honesty ratio and the realized
    packing fraction."""
    model = buildPacking(numSquares, seed, phiLow, softening, rigid = rigid)
    relax(model, tolerance, maxSteps)
    rows = []
    for phi in np.linspace(phiLow, phiHigh, points):
        model.setPackingFraction(phi)
        residual = relax(model, tolerance, maxSteps)
        areas = model.getAreas()[:numSquares]
        targets = np.asarray(model.getTargetAreas())[:numSquares]
        rows.append((phi, model.getEnergy(), residual,
                     float(np.abs(areas / targets - 1).max()), model.getPackingFraction()))
    return np.array(rows, dtype = [("phi", float), ("energy", float), ("residual", float),
                                   ("areaError", float), ("realized", float)])


def fitPowerLaw(phi, energy, gridPoints = 6000):
    """Fit ``E = A (phi - phi_J)^alpha`` by scanning phi_J and least-squaring in log-log.

    Three parameters, but only one is nonlinear: for any trial phi_J the remaining fit is a straight
    line through (log(phi - phi_J), log E). Scanning the one nonlinear parameter and keeping the best
    R^2 avoids handing a nonlinear solver an initial guess it can fail on, and the R^2 curve itself
    shows how sharply phi_J is determined. Returns (phi_J, alpha, prefactor, rSquared)."""
    phi = np.asarray(phi, dtype = float)
    energy = np.asarray(energy, dtype = float)
    good = energy > 0.0
    phi, energy = phi[good], energy[good]
    if phi.size < 3:
        return np.nan, np.nan, np.nan, np.nan
    y = np.log(energy)
    span = phi.max() - phi.min()
    best = (np.nan, np.nan, np.nan, -np.inf)
    for trial in np.linspace(phi.min() - 3.0 * span, phi.min() - 1e-6, gridPoints):
        x = np.log(phi - trial)
        slope, intercept = np.polyfit(x, y, 1)
        residual = y - (slope * x + intercept)
        rSquared = 1.0 - residual.var() / y.var() if y.var() > 0 else -np.inf
        if rSquared > best[3]:
            best = (trial, slope, np.exp(intercept), rSquared)
    return best


def logarithmicDerivative(phi, energy):
    """Fit alpha and phi_J from ``y = E / (dE/dphi)``, which is LINEAR in phi. Returns
    (phi_J, alpha, rSquared, y).

    This is the instrument to trust, and it is worth understanding why ``fitPowerLaw`` is not. Fitting
    ``E = A (phi - phi_J)^alpha`` directly has three parameters, only one of which is nonlinear, and
    over a narrow window alpha and phi_J trade off against each other almost perfectly -- measured on
    5 squares, halving sigma moved the pair from (3.00, 0.329) to (2.64, 0.573) while R^2 stayed at
    0.99999. A high R^2 there certifies smoothness, not correctness.

    Substituting the power law into the ratio kills the prefactor and linearizes what is left:

        E / (dE/dphi) = (phi - phi_J) / alpha,

    so an ordinary least-squares line gives alpha from its SLOPE (1/alpha) and phi_J from its
    x-intercept, with no nonlinear parameter to scan and no trade-off between them. Better still, the
    residuals are now a real test: if this plot is not straight, no single power law describes the data,
    which is the live question for polygons (a face-face contact gives alpha = 2 and a corner-into-face
    contact alpha = 4, so a mixture need not have one exponent at all).

    The cost is a numerical derivative, so feed it a smooth, well-converged sweep."""
    phi = np.asarray(phi, dtype = float)
    energy = np.asarray(energy, dtype = float)
    derivative = np.gradient(energy, phi)
    good = derivative > 0.0
    if good.sum() < 3:
        return np.nan, np.nan, np.nan, np.full(phi.shape, np.nan)
    y = np.full(phi.shape, np.nan)
    y[good] = energy[good] / derivative[good]
    slope, intercept = np.polyfit(phi[good], y[good], 1)
    residual = y[good] - (slope * phi[good] + intercept)
    rSquared = 1.0 - residual.var() / y[good].var() if y[good].var() > 0 else np.nan
    return -intercept / slope, 1.0 / slope, rSquared, y


def localExponent(phi, energy, phiJ):
    """Point-by-point ``d ln E / d ln(phi - phi_J)`` -- the exponent as a function of distance.

    A single fitted alpha is only meaningful if this is flat. For polygons it may well not be: the
    corner-contact term dies faster than the face-contact one, so the effective exponent should DRIFT
    downward toward 2 as phi_J is approached."""
    phi = np.asarray(phi, dtype = float)
    distance = phi - phiJ
    good = (distance > 0.0) & (np.asarray(energy) > 0.0)
    result = np.full(phi.shape, np.nan)
    result[good] = np.gradient(np.log(np.asarray(energy)[good]), np.log(distance[good]))
    return result


def linearIntercept(phi, energy, alpha):
    """x-intercept of ``E^(1/alpha)`` against phi -- the estimate of phi_J that a KNOWN exponent gives.

    This is the form worth using once the exponent is pinned down: it is an ordinary straight-line
    extrapolation from points safely above the transition, so it never needs a simulation at phi_J
    where the relaxation is critically slow. Returns (phi_J, rSquared)."""
    phi = np.asarray(phi, dtype = float)
    y = np.asarray(energy, dtype = float) ** (1.0 / alpha)
    slope, intercept = np.polyfit(phi, y, 1)
    residual = y - (slope * phi + intercept)
    rSquared = 1.0 - residual.var() / y.var() if y.var() > 0 else np.nan
    return -intercept / slope, rSquared


def pressure(phi, energy):
    """``P = phi dE/dphi`` by central differences -- the thermodynamic pressure for a unit box.

    With V the container area and phi = N A_p / V at fixed polygon size, dphi/dV = -phi/V, so
    P = -dE/dV = (phi/V) dE/dphi. Nothing new has to be computed: it falls out of the sweep. The
    independent check is the wall virial (total normal force on the container over its perimeter),
    which needs the container's own gradient that ``energies.containerEnergyForce`` currently skips
    when the wall is fully pinned."""
    return phi * np.gradient(np.asarray(energy, dtype = float), np.asarray(phi, dtype = float))


def findJammingDensity(numSquares, seed, softening, alpha, phiLow, phiHigh, points = 8,
                       rounds = 3, tolerance = 1e-9):
    """Locate phi_J by repeated linear extrapolation of ``E^(1/alpha)``, closing in each round.

    The point of a power law: rather than bisecting on a threshold, fit ABOVE the transition and
    extrapolate to zero energy. Each round re-sweeps a window that starts just above the current
    estimate, so the fit uses points progressively closer to phi_J without ever relaxing at it."""
    estimate = np.nan
    for _ in range(rounds):
        data = sweep(numSquares, seed, softening, phiLow, phiHigh, points, tolerance = tolerance)
        usable = data[data["energy"] > 0.0]
        if usable.size < 3:
            break
        estimate, _ = linearIntercept(usable["phi"], usable["energy"], alpha)
        width = phiHigh - phiLow
        phiLow = max(estimate + 0.05 * width, estimate + 1e-4)
        phiHigh = phiLow + 0.5 * width
    return estimate


def main():
    parser = argparse.ArgumentParser(description = __doc__)
    parser.add_argument("--squares", type = int, default = 5)
    parser.add_argument("--seeds", type = int, default = 3)
    parser.add_argument("--points", type = int, default = 12)
    parser.add_argument("--low", type = float, default = 0.70)
    parser.add_argument("--high", type = float, default = 0.90)
    args = parser.parse_args()
    warnings.simplefilter("ignore")

    print("=" * 88)
    print(f"energy sweep: {args.squares} rigid squares in a fixed unit container")
    print("=" * 88)

    print("\n[1] does the exponent depend on the mollification? (seed 0)")
    print("    softening   phi_J      alpha     R^2      E range")
    exponents = []
    for softening in (0.08, 0.04, 0.02):
        data = sweep(args.squares, 0, softening, args.low, args.high, args.points)
        phiJ, alpha, _, rSquared = fitPowerLaw(data["phi"], data["energy"])
        exponents.append((softening, phiJ, alpha, rSquared))
        print(f"      {softening:.3f}     {phiJ:.5f}   {alpha:.4f}   {rSquared:.5f}   "
              f"{data['energy'].min():.2e} .. {data['energy'].max():.2e}")
        print(f"                  worst residual {data['residual'].max():.1e}, "
              f"worst |A/A0 - 1| {data['areaError'].max():.1e}")
    spread = max(a for _, _, a, _ in exponents) - min(a for _, _, a, _ in exponents)
    print(f"    alpha spread across sigma: {spread:.4f} "
          f"({'sigma-independent' if spread < 0.15 else 'STILL sigma-dependent -- fit is contaminated'})")

    print("\n[2] the harmonic prediction alpha = 2")
    softening = 0.04
    data = sweep(args.squares, 0, softening, args.low, args.high, args.points)
    phiJ, alpha, _, rSquared = fitPowerLaw(data["phi"], data["energy"])
    harmonicPhiJ, harmonicR = linearIntercept(data["phi"], data["energy"], 2.0)
    freePhiJ, freeR = linearIntercept(data["phi"], data["energy"], alpha)
    print(f"    free fit      alpha = {alpha:.4f}   phi_J = {phiJ:.5f}   R^2 = {rSquared:.6f}")
    print(f"    sqrt(E) vs phi (alpha = 2 assumed): phi_J = {harmonicPhiJ:.5f}  R^2 = {harmonicR:.6f}")
    print(f"    E^(1/alpha) vs phi (fitted alpha):  phi_J = {freePhiJ:.5f}  R^2 = {freeR:.6f}")

    print("\n[3] pressure P = phi dE/dphi, and its exponent (expect alpha - 1)")
    P = pressure(data["phi"], data["energy"])
    usable = P > 0.0
    pPhiJ, pAlpha, _, pR = fitPowerLaw(data["phi"][usable], P[usable])
    print(f"    P exponent = {pAlpha:.4f}   (energy exponent - 1 = {alpha - 1.0:.4f})   "
          f"phi_J = {pPhiJ:.5f}   R^2 = {pR:.6f}")
    print("      phi        E            P")
    for row, p in zip(data, P):
        print(f"      {row['phi']:.4f}   {row['energy']:.6e}   {p:.6e}")

    print(f"\n[4] phi_J across seeds (protocol-dependent, unlike alpha)")
    found = []
    for seed in range(args.seeds):
        estimate = findJammingDensity(args.squares, seed, softening, alpha, args.low, args.high)
        found.append(estimate)
        print(f"    seed {seed}: phi_J = {estimate:.5f}")
    found = np.array(found, dtype = float)
    print(f"    mean {np.nanmean(found):.5f}  spread {np.nanmax(found) - np.nanmin(found):.5f}")
    print(f"    (densest known packing of {args.squares} squares is a separate quantity; a compressed "
          f"random branch jams at or below it)")


if __name__ == "__main__":
    sys.exit(main())
